name = "«ordinal-notation»"
defaultTargets = ["OrdinalNotation"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "OrdinalNotation"
